export const ADD_TO_CART_ITEM_REQUEST = "ADD_TO_CART_ITEM_REQUEST";
export const ADD_TO_CART_ITEM_SUCCESS = "ADD_TO_CART_ITEM_SUCCESS";
export const ADD_TO_CART_ITEM_FAILURE = "ADD_TO_CART_ITEM_FAILURE";

export const GET_TO_CART_REQUEST = "GET_TO_CART_REQUEST";
export const GET_TO_CART_SUCCESS = "GET_TO_CART_SUCCESS";
export const GET_TO_CART_FAILURE = "GET_TO_CART_FAILURE";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";


export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";